FROM golang:1.24

# Install Delve dependencies
RUN apt-get update && apt-get install -y \
    ca-certificates \
    git \
    build-essential

# Install Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app

COPY . .

# Build with debug symbols
RUN go build -gcflags "all=-N -l" -o altcha-server .


# Run Delve in headless mode
CMD ["dlv", "exec", "/app/altcha-server", "--headless", "--listen=:40000", "--api-version=2", "--accept-multiclient"]


